import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/organisms/AppHeader";
import { AppFooter } from "@/components/organisms/AppFooter";
import { orbit, inter, orbitron, grandiflora } from "./font";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${orbit.variable}
          ${inter.variable}
          ${orbitron.variable}
          ${grandiflora.variable}
          bg-neutral-100
          text-neutral-900
            antialiased
        `}
      >
        <AppHeader />
        <main className="min-h-screen flex items-center justify-center">
          {children}
        </main>
        {/* <AppFooter /> */}
      </body>
    </html>
  );
}
